name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        rails-version: [3, 4, 5, 7]

    name: Test on Rails v${{ matrix.rails-version }}

    env:
      BUNDLE_GEMFILE: "gemfiles/rails_${{ matrix.rails-version }}.gemfile"
      BUNDLE_GEMS__RAILSLTS__COM: ${{ secrets.RAILS_LTS_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests
        run: bundler exec rake rspec${{ matrix.rails-version }}
